[browser]
showSidebarNavigation = false

[theme]
primaryColor="#0fc32e"
backgroundColor="#353333"
secondaryBackgroundColor="#000000"
textColor="#f7f5f5"


[server]
enableCORS = false
enableXsrfProtection = true

[runner]
fastReruns = true

[client]
toolbarMode = "minimal"
